/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AtAnchor: typeof import('./src/components/markdown-elements/AtAnchor.vue')['default']
    AtImg: typeof import('./src/components/markdown-elements/AtImg.vue')['default']
    AtLink: typeof import('./src/components/markdown-elements/AtLink.vue')['default']
    AtStyle: typeof import('./src/components/markdown-elements/AtStyle.vue')['default']
    AtWebStylesheet: typeof import('./src/components/markdown-elements/AtWebStylesheet.vue')['default']
    AtWebTitle: typeof import('./src/components/markdown-elements/AtWebTitle.vue')['default']
    BlueskyPost: typeof import('./src/components/markdown-elements/BlueskyPost.vue')['default']
    BlueskyProfileCard: typeof import('./src/components/markdown-elements/BlueskyProfileCard.vue')['default']
    BlueskyProfileFeed: typeof import('./src/components/markdown-elements/BlueskyProfileFeed.vue')['default']
    EightyEightThirtyOneBadge: typeof import('./src/components/markdown-elements/EightyEightThirtyOneBadge.vue')['default']
    LesbiBadge: typeof import('./src/components/markdown-elements/LesbiBadge.vue')['default']
    MarkdownRenderer: typeof import('./src/components/MarkdownRenderer.vue')['default']
    MonacoEditor: typeof import('./src/components/MonacoEditor.vue')['default']
    NewBlink: typeof import('./src/components/markdown-elements/NewBlink.vue')['default']
    NewMarquee: typeof import('./src/components/markdown-elements/NewMarquee.vue')['default']
    OmitVanillaCss: typeof import('./src/components/markdown-elements/OmitVanillaCss.vue')['default']
    OnekoKitty: typeof import('./src/components/markdown-elements/OnekoKitty.vue')['default']
    PModal: typeof import('./src/components/PModal.vue')['default']
    RenderJson: typeof import('./src/components/markdown-elements/RenderJson.vue')['default']
    RingLink: typeof import('./src/components/markdown-elements/RingLink.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignInGate: typeof import('./src/components/SignInGate.vue')['default']
    SocialLink: typeof import('./src/components/markdown-elements/SocialLink.vue')['default']
    SpotifyPlayer: typeof import('./src/components/markdown-elements/SpotifyPlayer.vue')['default']
    UsePico: typeof import('./src/components/UsePico.vue')['default']
    UserbarBadge: typeof import('./src/components/markdown-elements/UserbarBadge.vue')['default']
    WebampPlayer: typeof import('./src/components/markdown-elements/WebampPlayer.vue')['default']
  }
}
